#!/bin/bash
export HTTP_PORT=9090
export JDBC_URL="jdbc:mysql://dev:3307/S61?useUnicode=true&characterEncoding=utf-8&noAccessToProcedureBodies=true"
#export RSAKEY_PATH="/opt/hry/javaapps/rsaprivatekey.pem"
#export RSAKEY_PASSWORD="123456"
exec jstart user
